### basic settings

# site properties and page defaults
title: SARS-CoV-2 Genetic Interactions in Yeast
description: A website for my ongoing research on SARS-CoV-2 genetic interactions in yeast in Rodney Rothstein's Lab at Columbia University.
logo: images/logo.svg
header: images/background.jpg
footer: images/background.jpg
baseurl: /lab-website-template

# site social media and other links
links:
  email: yinghan@caltech.edu
  google-scholar: Megan Wang
  github: https://github.com/meganwang08
  #twitter: YourLabHandle
  #instagram: YourLabHandle
  #youtube: YourLabChannel

### advanced settings

# default front matter parameters for markdown files
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

# collections
collections:
  members:
    output: true

# sass settings
sass:
  sass_dir: css

# syntax highlighting
highlighter: rouge

# plugins
plugins:
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-sitemap
  # - jekyll-github-metadata
  # - jekyll-avatar
  # - jekyll-gist
  # - jekyll-mentions
  # - jekyll-relative-links
  # - jemoji

# jekyll theme
theme: null
